sudo: required

services: docker

env:
  matrix:
    - LOCO_VERSION=v4.0.x-20190709 WAGON_VERSION=v4.0.x-20190528

before_install:
  - sudo pip install docky
  - ./travis/install

script:
  - docker build --no-cache -t current-latest --build-arg version=$LOCO_VERSION demo

after_success:
- ./travis/publish
